import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:agent_code_client_app/ui/streaming_markdown.dart';

/// Conformance test against the reference implementation this was ported from
/// (qm's `plugins/web-ui/src/streaming-markdown.ts`).
///
/// `test/fixtures/streaming_markdown_reference.json` holds 514 cases — hand-written
/// edge cases, every prefix of a realistic streamed reply, and 300 randomized
/// fuzz inputs — each paired with the output the original produces. The fixture
/// was generated by running the TypeScript directly, so this pins behaviour to
/// the source of truth rather than to a re-reading of it.
///
/// Regenerate by re-running the original over `text`/`quantum` and recording
/// `stable`, `segments`, and `tail`.
void main() {
  late List<dynamic> reference;

  setUpAll(() {
    final file = File('test/fixtures/streaming_markdown_reference.json');
    reference = jsonDecode(file.readAsStringSync()) as List<dynamic>;
  });

  test('fixture is present and substantial', () {
    expect(reference.length, greaterThan(500));
  });

  test('matches the reference implementation on every case', () {
    final mismatches = <String>[];

    for (final raw in reference) {
      final c = raw as Map<String, dynamic>;
      final name = c['name'] as String;
      final text = c['text'] as String;
      final quantum = c['quantum'] as int;

      final stable = stableSplitPoint(text);
      if (stable != c['stable']) {
        mismatches.add('$name: stableSplitPoint ${c['stable']} -> $stable');
      }

      final split = splitStreamingMarkdown(text, quantum: quantum);
      final expectedSegments = (c['segments'] as List).cast<String>();
      if (!_listEquals(split.segments, expectedSegments)) {
        mismatches.add(
          '$name: segments ${expectedSegments.length} -> ${split.segments.length}',
        );
      }
      if (split.tail != c['tail']) {
        mismatches.add('$name: tail differs');
      }
    }

    expect(mismatches, isEmpty,
        reason: 'diverged from the reference on:\n${mismatches.take(20).join('\n')}');
  });

  test('segments and tail reconstruct the input on every case', () {
    for (final raw in reference) {
      final c = raw as Map<String, dynamic>;
      final text = c['text'] as String;
      final split = splitStreamingMarkdown(text, quantum: c['quantum'] as int);
      expect(split.segments.join() + split.tail, text,
          reason: 'lossy split for ${c['name']}');
    }
  });
}

bool _listEquals(List<String> a, List<String> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
